---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: java-app
  namespace: default
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: "devopshint/my-app-1.0:latest"
        ports:
          - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: java-app
  namespace: default
spec:
  selector:
    app: java-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 8081
    port: 80